language: python

python:
  - 2.7
  - 3.4
  - 3.5

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - pip install Cython
  - pip install numpy
  - pip install matplotlib
  - pip install iminuit
  - pip install pytest pytest-cov pytest-mpl
  - pip install flake8 pylint
  # ipython needed for docs: IPython.sphinxext.ipython_directive
  - pip install ipython sphinx sphinx_rtd_theme

script:
  - make flake8
  - make pylint
  - make test
  - cd doc && make html
