language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
    - "pip install matplotlib --use-mirrors"
    - "git clone git://github.com/piti118/iminuit.git; cd iminuit; python setup.py install; cd .."
# command to run tests
script:
    - "python setup.py build_ext -i"
    - "nosetests"
